# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.9'

# Define services
services:
  # Database Service (Mysql)
  mysql2:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password1
      - MYSQL_DATABASE=book_store
    volumes:
      - ./init_sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mongo:
    container_name: mongo
    image: mongo:5.0.5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    networks:
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - mysql
# Volumes
volumes:
  mysql_data:
    driver: local
# Networks to be created to facilitate communication between containers
networks:
  backend:
  auth-network:
    driver: bridge  
